name: Deploy to Workshop

on:
  workflow_dispatch:
    inputs:
      changelog:
        type: string
        required: false
        default: "Update to latest Git commit"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: project

      - name: Remove Non-content
        run: |
          rm -rfv $GITHUB_WORKSPACE/project/_project
          rm -rfv $GITHUB_WORKSPACE/project/.git
          rm -rfv $GITHUB_WORKSPACE/project/.github

      - uses: CFC-Servers/gmod-upload@master
        with:
          id: 3114943116
          changelog: 3460538108
          title: gm_tests_map
          type: map
          tag1: build
        env:
          STEAM_USERNAME: ${{ secrets.WORKSHOP_UPLOADER_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WORKSHOP_UPLOADER_PASSWORD }}
